baseurl = "https://exception.blog/"
languageCode = "pt-br"
theme = "terminal"
paginate = 5

[params]
contentTypeName = "posts"
themeColor = "red"
showMenuItems = 2
fullWidthTheme = false
centerTheme = true
favicon = "favicon.png"

[languages]
[languages.en]
title = "Jojo's Exceptions"
subtitle = "Meus surtos e momentos de coerência."
keywords = ""
copyright = ""
menuMore = "Ver mais"
readMore = "Ler mais"
readOtherPosts = "Mais groselha"

[languages.en.params.logo]
logoText = "exception"
logoHomeLink = "/"

[languages.en.menu]
[[languages.en.menu.main]]
identifier = "whois"
name = "whois"
url = "/about"
